### ISSUE TITLE
Diff fails with "Fail to get the file revision (Error 1)"

### ISSUE THREAD

**Issue by dddonovan** [Jaimecclin/cvs-pluging-vscode-ext#1] opened 2022-06-01 17:39 UTC
I am using VS Code on Windows via Remote WSL Server.  The CVS Panel shows all folders in my multi-root workspace, and the update functions show changed files properly.  I can also use the 'open file' icon button successfully.

However, the diff does not work, I get an error notification instead
"Fail to get the file revision (Error 1)"

I didn't see any logging from the extension in the Output panel, so I don't have anything else to help troubleshoot, but if you let me know where to look happy to provide more info.

**Comment by Jaimecclin** [comment] 2022-06-02 00:55
Hi dddonovan

Just a quick response. You can try the diff button again, or more times. To me, it works. And I will look into the code soon. Let's see how to solve it. Thanks for your kind information.

**Comment by dddonovan** [comment] 2022-06-02 14:56
Hi,

Thanks for the quick reply and I want to say thanks for making a CVS extension anyway for us devs trapped into using it :) .  Repeated attempts did not work for me.  I found some logging in the 'WhiteBoard' output:

```
Logger is initialized
Workspace folder 0 , name :Devel
Workspace folder 1 , name :QA
Workspace folder 2 , name :Prod
setSelectedFile:Devel
setSelectedFile:QA
setSelectedFile:cgi-bin/Util.pm
grep command is closing
grep command is closing
grep command is closing
grep command is closing
grep command is closing
grep command is closing
grep command is closing
```

The `grep command is closing` output is printed each time I click, but I am still getting the same issue, no diff opens and I get an error notification for "Fail to get the file revision (Error 1)"

I did have one thought.  My workspace folders are using aliases via the `name` key.  Perhaps this is not accounted for.

```json
	"folders": [
		{
			"name": "Devel",
			"uri": "vscode-remote://wsl+ubuntu/home/ddonovan/code/devel/project_www"
		}
		,{
			"name": "QA",
			"uri": "vscode-remote://wsl+ubuntu/home/ddonovan/code/qa/project_www"
		}
		,{
			"name": "Prod",
			"uri": "vscode-remote://wsl+ubuntu/home/ddonovan/code/prod/project_www"
		}
	],
```

**Comment by Jaimecclin** [comment] 2022-06-02 15:05
Hi
Could you help to test one thing in your environment? Please try this command and post the result. It will be very helpful.
```
// $filepath is the relative path to your cvs root
// Test this command at your CVS folder root position
cvs -bSN log $filepath | head -n 50
```
Thanks!

**Comment by dddonovan** [comment] 2022-06-02 15:22
The `-bSN` switches will not apply to the log command if they are before the string 'log'.  

Here is the output of the command as you pasted:
```

RCS file: /opt/cvs/repos/project_www/cgi-bin/Util.pm,v
Working file: cgi-bin/Util.pm
head: 120.4
branch:
locks: strict
access list:
symbolic names:
        April22-qa: 120.0.0.2
        March22-prod: 119.0.2.7.0.2
        May22-devel: 120.0
        March22-qa: 119.0.0.2
        February22-prod: 118.0.2.3.0.2
        April22-devel: 119.0
        February22-qa: 118.0.0.2
        January22-prod: 117.0.2.7.0.2
        March22-devel: 118.0
        January22-qa: 117.0.0.2
        November21-prod: 116.0.2.13.0.2
        February22-devel: 117.0
        November21-qa: 116.0.0.2
        October21-prod: 115.0.2.23.0.2
        January22-devel: 116.0
        October21-qa: 115.0.0.2
        September21-prod: 114.0.2.7.0.2
        November21-devel: 115.0
        September21-qa: 114.0.0.2
        August21-prod: 113.0.2.18.0.2
        October21-devel: 114.0
        August21-qa: 113.0.0.2
        July21-prod: 112.0.2.8.0.2
        September21-devel: 113.0
        July21-qa: 112.0.0.2
        June21-prod: 111.0.2.10.0.2
        August21-devel: 112.0
        June21-qa: 111.0.0.2
        May21-prod: 110.0.2.12.0.2
        July21-devel: 111.0
        May21-qa: 110.0.0.2
        April21-prod: 109.0.2.8.0.2
        June21-devel: 110.0
        April21-qa: 109.0.0.2
        March21-prod: 108.0.2.4.0.2
        May21-devel: 109.0
        March21-qa: 108.0.0.2
        February21-prod: 107.0.2.13.0.2
        April21-devel: 108.0
        February21-qa: 107.0.0.2
        January21-prod: 106.0.2.17.0.2
        March21-devel: 107.0
cvs [log aborted]: received broken pipe signal
cvs [log aborted]: write error
```
here is output with switches moved ( `cvs log -bSN cgi-bin/Util.pm | head -n 50` ):

```
RCS file: /opt/cvs/repos/project_www/cgi-bin/Util.pm,v
Working file: cgi-bin/Util.pm
head: 120.4
branch:
locks: strict
access list:
keyword substitution: kv
total revisions: 6544;  selected revisions: 5
description:
----------------------------
revision 120.4
date: 2022/06/02 00:55:28;  author: ddonovan;  state: Exp;  lines: +8 -5
ftp_put_file() - fix arg list for setcwd
----------------------------
revision 120.3
date: 2022/06/01 22:04:56;  author: redacted;  state: Exp;  lines: +14 -3
TT 29862: Need to 0 out blank rev_type_ind value in util_withdraw_user()
----------------------------
revision 120.2
date: 2022/06/01 17:14:45;  author: ddonovan;  state: Exp;  lines: +18 -10
ftp_put_file
- use setcwd for Net::SFTP::Foreign dir change, more compatible and we don't need folder contents
----------------------------
revision 120.1
date: 2022/05/24 05:28:14;  author: redacted;  state: Exp;  lines: +201 -16
TTS 28445 - draft of brute force workaround using &dbdt_calendar_negative_delta_bruteforce()
TTS 28328 - util_category_dropdown_group_get() - new public function
----------------------------
revision 120.0
date: 2022/05/24 02:22:43;  author: redacted;  state: Exp;  lines: +11 -3
branches:  120.0.2;
May22 primary version
=============================================================================
```

**Comment by Jaimecclin** [comment] 2022-06-02 15:50
Hi
That's very interesting. Could you provide your CVS version?
Try this: `cvs --version`

In my environment, both `cvs log -bSN cgi-bin/Util.pm` and `cvs -bSN log cgi-bin/Util.pm` work fine. Fortunately, I can quickly fix this problem. I plan to have a hotfix within two days. After updating this extension, I will update this thread to notify you. I would appreciate it If you can try it again.

Btw, I think doing some updates on the logger is on my list. Thanks for your great help again.

**Comment by Jaimecclin** [comment] 2022-06-02 16:56
Hi
I've updated it. https://marketplace.visualstudio.com/items?itemName=jaimelin.cvs-plugin
Please try it if you're available. Hope it solves your problem.

Happy Dragon Boat Day :)

**Comment by dddonovan** [comment] 2022-06-02 21:47
Hi,  The diff opens now, but it is using the wrong revision
```
Linux exe cmd: `cvs log -bSN cgi-bin/Util.pm`
Linux exe cmd: `head -n 50`
Linux exe cmd: `grep -m 1 -Po revision d*.d*`
Linux exe cmd: `tr -d revision `
grep command is closing
checkout file path: project_www/cgi-bin/Util.pm
Linux exe cmd: `cvs co -p -r 1 project_www/cgi-bin/Util.pm`
===================================================================
Checking out project_www/cgi-bin/Util.pm
RCS:  /opt/cvs/repos/project_www/cgi-bin/Util.pm,v

VERS: 1.74
***************

tempFileName:rev-1-cgi-bin-Util.pm
tempFilePath:/home/ddonovan/.vscode-server/extensions/jaimelin.cvs-plugin-0.2.6/temporary/rev-1-cgi-bin-Util.pm
```

Seems like it is parsing the revision incorrectly.

Here is some commands I tired from repo root, the first one copied directly from the logs, the second 2 after adding some quotes and escapes.

```
ddonovan@machine:~/code/prod/project_www$ cvs log -bSN cgi-bin/Util.pm | head -n 50 | grep -m 1 -Po revision d*.d*
grep: d*.d*: No such file or directory
ddonovan@machine:~/code/prod/project_www$ cvs log -bSN cgi-bin/Util.pm | head -n 50 | grep -m 1 -Po "revision \d*.\d*"
revision 120.4
ddonovan@machine:~/code/prod/project_www$ cvs log -bSN cgi-bin/Util.pm | head -n 50 | grep -m 1 -Po "revision \d*.\d*" | tr -d "revision "
120.4
```

Consider this command to get a copy of the latest commited version without local changes (and no side effects)

```
cvs -Q up -C -p cgi-bin/Util.pm
```
(Note: assumes cwd is on the proper branch)

🐉⛵🎇

**Comment by Jaimecclin** [comment] 2022-06-03 05:44
Hi
You're right. There is some trouble when getting the head revision. The CVS command is a bit cumbersome and yours looks better. I adapted the command in the latest commit. Could you give it a try?

Btw, ur name is mentioned in `README.md` to thank you.

**Comment by Jaimecclin** [comment] 2022-06-06 06:15
Wait a minute...  Sorry, it seems there is some trouble.

**Comment by Jaimecclin** [comment] 2022-06-06 13:03
A new patch is pushed. I think the problem is fixed and there is no more response. Close it. We can reopen it if needed.

**Closed as completed by Jaimecclin** 2022-06-06 13:03 UTC

**Comment by dddonovan** [comment] 2022-06-11 08:05
Hi,

Just wanted to say thanks for the quick turnaround and looking forward to the completed extension

Cheers
